### ISSUE TITLE
Script Fails When Issuing Let's Encrypt SSL

### ISSUE THREAD

**Issue by jmessy919** [abrefael/ERP-Next-15-installation-script#1]
The script fails when it attempts to issue the SSL for the site.

The script tries to use the Sudo User's password as the Let's Encrypt email address, resulting in a failed SSL issuance.

This breaks the remainder of the process, unfortunately.

**Comment by abrefael** [comment]
Guess you were right.
I was piping `sudo`'s password to the command so the user will not need to type it.
Probably wasn't the right call.
Thanks for your input.

**Comment by jmessy919** [comment]
Of course. Thanks for doing your best to simplify the installation process for ERPNext - I appreciate you.

**Comment by jmessy919** [comment]
Works perfectly with the latest update. I have tried many different methods to install ERPNext, and yours is the only one that worked for me. I just want you to know, you have made an amazing impact on my life and my business. Can I send you some coin for a coffee? Cheers, @abrefael 🍻

**Comment by abrefael** [comment]
Happy to help. I'm here for the pats on the back.
Just "pay it forward".
